config/routes.rb
Rails.application.routes.draw do

  resources :users do
    post 'add_friend', as: :add_friend
  end

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register', edit: 'settings' }

  root to: 'users#index'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  has_many :friendships
  has_many :friends, through: :friendships

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :first_name, :last_name, :website

  after_validation :shorten_url, :fetch_headers, if: :website_changed?

  def full_name
    "#{first_name} #{last_name}"
  end

  def fetch_headers
    page = Nokogiri::HTML(open(website))
    raw_headers = page.css('h1,h2,h3').sort_by { |h| h.name }
    self.headers = raw_headers.map{ |h| {h.name => h.text} if h.text.present? }.compact
    self.headers.map { |h| h.map{|k,v| self.searchable << v } }
  end

  def befriend(user)
    self.friends << user
    user.friends << self
  end

  def can_befriend?(user)
    !(friends.include?(user) || self == user)
  end

  def self.search(search)
    if search
      where('searchable ilike ?', "%#{search}%")
    else
      all
    end
  end

  def shorten_url
    response = `curl https://www.googleapis.com/urlshortener/v1/url?key=#{ENV['GOOGLE_API_KEY']} \
      -H 'Content-Type: application/json' \
      -d '{"longUrl": "#{website}"}'`
    json = JSON.parse(response)
    self.short_url = json["id"]
    self.website   = json["longUrl"]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :website])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :website])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.search(params[:search])
  end

  def show
    @user = User.find(params[:id])
  end

  def add_friend
    user = User.find(params[:user_id])
    if current_user.befriend(user)
      redirect_to users_path, flash: {notice: "You are now friends with #{user.full_name}"}
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  # A simple way to show error messages for the current devise resource. If you need
  # to customize this method, you can either overwrite it in your application helpers or
  # copy the views to your application.
  #
  # This method is intended to stay simple and it is unlikely that we are going to change
  # it to add more behavior or options.
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      count: resource.errors.count,
                      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <p>#{sentence}</p>
    <ul>#{messages}</ul>
    HTML

    html.html_safe
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navigation.html.erb
<ul class="nav navbar-nav navbar-right">
  <% if current_user %>
    <li><%= link_to('<span class="glyphicon glyphicon-cog"></span> Settings'.html_safe, edit_user_registration_path) %></li>
    <li><%= link_to('<span class="glyphicon glyphicon-off"></span> Log out'.html_safe, destroy_user_session_path, method: 'delete') %></li>
  <% else %>
    <li><%= link_to('<span class="glyphicon glyphicon-log-in"></span> Login'.html_safe, new_user_session_path) %></li>
    <li><%= link_to('<span class="glyphicon glyphicon-saved"></span> Register'.html_safe, new_user_registration_path) %></li>
  <% end %>
</ul>

app/views/layouts/_notifications.html.slim
- if notice
  .alert.alert-info
    p= notice

- if alert
  .alert.alert-warning
    p= alert

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
	  <title><%= content_for?(:title) ? yield(:title) + 'Experts Directory' : 'Experts Directory' %></title>
	  <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	  <%= csrf_meta_tags %>

  </head>

  <body>
	  <nav class="navbar navbar-default">
		  <div class="container-fluid">
			  <div class="navbar-header">
				  <button type="button" class="navbar-toggle collapsed"
				          data-toggle="collapse" data-target="#menu-collapse">
					  <span class="sr-only">Toggle navigation</span>
					  <span class="icon-bar"></span>
					  <span class="icon-bar"></span>
					  <span class="icon-bar"></span>
				  </button>
				  <%= link_to 'Experts Directory', root_path, class: 'navbar-brand' %>
          <% if current_user %>
            <%= form_tag(users_path, method: 'get', class: 'navbar-form navbar-right') do %>
              <%= search_field_tag :search, params[:search], class: 'form-control', placeholder: 'Search Experts'  %>
              <%= submit_tag 'Search', class: 'btn btn-default', :name => nil %>
            <% end %>
          <% end %>
			  </div>

			  <div class="collapse navbar-collapse" id="menu-collapse">

				  <%= render 'layouts/navigation' %>

			  </div>
		  </div>
	  </nav>

	  <div class="container">
		  <%= render 'layouts/notifications' %>

      <%= yield %>
	  </div>
  </body>
</html>

app/views/users/index.html.slim
h1 Experts Index

- if @users.empty?
  p No Users

- else
  table.table.table-striped.table-bordered.table-hover
    thead.text-uppercase
      tr
        th Email Address
        th Website
        th Friend Count
        th Add Friend
    tbody
      - @users.each do |user|
        tr
          td= link_to user.full_name, user_path(user)
          td= link_to user.short_url, user.short_url, target: '_blank'
          td= user.friends.count
          - if current_user.can_befriend?(user)
            td= link_to 'Add Friend', user_add_friend_path(user), class: 'btn btn-primary active', method: :post
          - else
            td
              button type='button' class='btn btn-primary disabled' Add Friend 

app/views/users/show.html.slim
div.container.col-lg-6
  - @user.headers.each do |header|
    = header.map{|k,v| "<#{k}>#{v}</#{k}>"}.first.html_safe
div.container.col-lg-6.text-right
  h1= @user.full_name
  h4= link_to @user.website, @user.website, target: '_blank'
  h4= link_to @user.short_url, @user.short_url, target: '_blank'
  div
    h2= "Friends (#{@user.friends.count})"
    - if @user.friends.present?
      - @user.friends.each do |friend|
        p= link_to friend.full_name, user_path(friend)
    - else
      p This user has no friends